### ISSUE TITLE
Message Limitations and Speed of RSU Communication with Nodes

### ISSUE THREAD

**Issue by Y-AMDIAZ** [dnatividade/VEINS-tutorials#4]
Hi , I have a question about the communication process between RSUs (Roadside Units) and nodes. Is there a limit on the number of messages that RSUs can send, and if we send a large volume of messages from RSUs, could there be a situation where some messages may not be sent, or the process becomes slower ?

**Comment by dnatividade** [comment]
Hi.

I don't know if there is a limit for sending messages, but I believe there is no limitation.
But with a massive sending of messages, the simulation will take a long time to complete, the time will depend on your hardware. In these cases, the simulation must be carried out on the command line (without using Qt for the graphical interface).

As for messages not being delivered, this will only happen if there are: collisions, a lot of noise on the channel, obstacles or outside the coverage area. Because all these questions are addressed in the simulator.

**Comment by dnatividade** [comment]
Sorry, but I don't think I understood your question.

**Comment by dnatividade** [comment]
You want to see statistics about your simulation, right?
https://www.youtube.com/watch?v=bQriZ_DvbW0
![statistics](https://github.com/dnatividade/VEINS-tutorials/assets/43869367/9c770cb0-ecdf-45da-bd5a-9a59c2e6507d)

**Comment by dnatividade** [comment]
But you can also create your own statistics by collecting the data in your code and saving it to a text file to later check or plot the results.

**Comment by dnatividade** [comment]
EDIT: 

To enable collision statistics, add in your ominetpp.ini:
```*.**.nic.phy80211p.collectCollisionStatistics = true```

source: https://stackoverflow.com/questions/52100969/how-to-get-collisions-in-veins-4-7-1

**Comment by Y-AMDIAZ** [comment]
hi dnatividade I have a question did you used simuLTE or simu5G  befor or not ?

**Comment by dnatividade** [comment]
No.

**Comment by Y-AMDIAZ** [comment]
just a little erreur when I ran my simulation it gives me erreur 
<img width="807" alt="image" src="https://github.com/dnatividade/VEINS-tutorials/assets/129278941/def1f854-2809-4d30-ba43-b6c205cab207">
<img width="838" alt="image" src="https://github.com/dnatividade/VEINS-tutorials/assets/129278941/4ff60e67-b6d1-4055-908e-30e610658e58">
because I download another omnet++ and another veins I took my last project so I change my Traci fils by the last traci and a exemple fils by my exmple so finaly it gives me that

**Comment by dnatividade** [comment]
Hi.
Try a "make clean" as indicated in the generated code.

*_m.h files are automatically generated. You probably generated it using an earlier version.

**Comment by Y-AMDIAZ** [comment]
where I can try "make clean" just I write it on the omnet.ipi or what ?

**Comment by Y-AMDIAZ** [comment]
I want to incorporate RSU (Roadside Unit) into my simulation simuLte to receive messages from cars and send them to eNodeB1. However, I'm encountering challenges when adding it, and I'm seeking guidance on where and how to modify the setup to facilitate communication. Can you please help? but where I can modify to creat a communication betwenne RSU and eNodeB ?? please if you have any idea about that ?? im blocking here 
<img width="784" alt="image" src="https://github.com/dnatividade/VEINS-tutorials/assets/129278941/884e4587-907f-40db-b3ed-ad7f56781760">

<img width="488" alt="image" src="https://github.com/dnatividade/VEINS-tutorials/assets/129278941/af695bbb-b2cc-49db-92ae-f5d6c93a9e82">
<img width="700" alt="image" src="https://github.com/dnatividade/VEINS-tutorials/assets/129278941/0773d549-cb85-4c8f-a1c8-a092479f28d9">

**Comment by dnatividade** [comment]
> where I can try "make clean" just I write it on the omnet.ipi or what ?


https://github.com/dnatividade/VEINS-tutorials/assets/43869367/3046e4af-8f1c-4306-8c6e-e898d13fe94a

**Comment by dnatividade** [comment]
I don't work with simulLTE. However, I can give an example using just Veins with vehicles and an RSU. Would that swear you?
Please, to maintain organization, create a new issue with this theme.

**Comment by dnatividade** [comment]
> I don't work with simulLTE. However, I can give an example using just Veins with vehicles and an RSU. Would that swear you? Please, to maintain organization, create a new issue with this theme.



> I want to incorporate RSU (Roadside Unit) into my simulation simuLte to receive messages from cars and send them to eNodeB1. However, I'm encountering challenges when adding it, and I'm seeking guidance on where and how to modify the setup to facilitate communication. Can you please help? but where I can modify to creat a communication betwenne RSU and eNodeB ?? please if you have any idea about that ?? im blocking here <img alt="image" width="784" src="https://private-user-images.githubusercontent.com/129278941/309818312-884e4587-907f-40db-b3ed-ad7f56781760.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzU3MTIsIm5iZiI6MTcwOTYzNTQxMiwicGF0aCI6Ii8xMjkyNzg5NDEvMzA5ODE4MzEyLTg4NGU0NTg3LTkwN2YtNDBkYi1iM2VkLWFkN2Y1Njc4MTc2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQxMDQzMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYzhmMDlmYmE1YmViMWQ0NWM0ZjVmMGRkMDY3NGQxNWIwY2IwZDI3YzFjNmNlN2I2MTdkYmMxNzYzNjBlYzJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OhYtcjXzqfeJPUGREM7_s1gxu0rwh_QRJ8QdFkNmRHo">
> <img alt="image" width="488" src="https://private-user-images.githubusercontent.com/129278941/309817673-af695bbb-b2cc-49db-92ae-f5d6c93a9e82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzU3MTIsIm5iZiI6MTcwOTYzNTQxMiwicGF0aCI6Ii8xMjkyNzg5NDEvMzA5ODE3NjczLWFmNjk1YmJiLWIyY2MtNDlkYi05MmFlLWY1ZDZjOTNhOWU4Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQxMDQzMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNjJjMzcxMTg5NDU5OTNmY2I2MWM3YzYzYzg3NDM0YjFmMWZjZTA3MDBlZTVkYmQzMjFhZjRkMGFmZTRhZWJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hr3Mzu2I0zNMsxZxS1R2cn7rzPh2p-7gevGBY6AaPR8"> <img alt="image" width="700" src="https://private-user-images.githubusercontent.com/129278941/309818945-0773d549-cb85-4c8f-a1c8-a092479f28d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzU3MTIsIm5iZiI6MTcwOTYzNTQxMiwicGF0aCI6Ii8xMjkyNzg5NDEvMzA5ODE4OTQ1LTA3NzNkNTQ5LWNiODUtNGM4Zi1hMWM4LWEwOTI0NzlmMjhkOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQxMDQzMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNWY2YzMwNzllYWVkZTBlMDFjODI2Zjg1NGM1NTU2N2M1OWEyODI0MmRjOTNjYWZkZWQyZDhkN2EzYWZkNmYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.V8F4vYfXg7hcXUPo_oBO9s7Z3AZpcfFbux5hakLVU7A">

I don't work with simulLTE. However, I can give an example using just Veins with vehicles and an RSU. Would that swear you?
Please, to maintain organization, create a new issue with this theme.
