### ISSUE TITLE
ADDing a RSU on the simulation to reciev a message from cars and send it to eNodesBX veins 

### ISSUE THREAD

**Issue by Y-AMDIAZ** [dnatividade/VEINS-tutorials#7]
I want to incorporate RSU (Roadside Unit) into my simulation simuLte to receive messages from cars and send them to eNodeB1. However, I'm encountering challenges when adding it, and I'm seeking guidance on where and how to modify the setup to facilitate communication. Can you please help? but where I can modify to creat a communication betwenne RSU and eNodeB ?? please if you have any idea about that ?? im blocking here 
<img width="784" alt="image" src="https://github.com/dnatividade/VEINS-tutorials/assets/129278941/884e4587-907f-40db-b3ed-ad7f56781760">

<img width="488" alt="image" src="https://github.com/dnatividade/VEINS-tutorials/assets/129278941/af695bbb-b2cc-49db-92ae-f5d6c93a9e82">
<img width="700" alt="image" src="https://github.com/dnatividade/VEINS-tutorials/assets/129278941/0773d549-cb85-4c8f-a1c8-a092479f28d9">

**Comment by dnatividade** [comment]
Take a look at this example. This is a simple scenario where the RSU continuously sends messages to vehicles.
https://github.com/dnatividade/Vanet-Projects/tree/main/01%20Simple%20Projects/001%20Send%20broadcast%20msg%20from%20RSU%20to%20cars%20continuously

**Comment by Y-AMDIAZ** [comment]
But this is specific to veins, and I'm aware that I've used RSU in veins before. What I'm aiming for now is utilizing RSU in a different environment, similar to LTEsimu. When I integrate RSU into this simulation, what modifications should I make to establish communication between the RSU and another device, akin to eNodeB1 ?

**Comment by Y-AMDIAZ** [comment]
I add a RSU in this picture on the simulation 
<img width="500" alt="image" src="https://github.com/dnatividade/VEINS-tutorials/assets/129278941/16592f87-ccc6-40a1-b312-f3c8e533eb24">
I take a RSU setting and I add it on the omnet.ini of our simulation 
<img width="700" alt="image" src="https://github.com/dnatividade/VEINS-tutorials/assets/129278941/2f457b58-2046-4122-959c-16fa2beceb17">
the result 
<img width="787" alt="image" src="https://github.com/dnatividade/VEINS-tutorials/assets/129278941/f787ff12-5e05-40cc-8dc6-7eb3adf8ca23">

**Comment by dnatividade** [comment]
This message is appearing because your configuration file (omnetpp.ini) is missing parameters.
But unfortunately I won't be able to help you with this issue, as I only work with Veins.

I'm sorry I couldn't help you more.
